import fs from "node:fs";
import {
  changeCaseTo,
  getFileExtension,
  getFilenameWithoutExtension,
} from "@gyldendal/kobber-base/utilities/index.js";

export { listReactComponents } from "./list-react-components";
export { listWebComponents } from "./list-web-components";

export type ComponentObject = {
  importComponent: string;
  importPath: string;
  exportName: string;
  exportTagName: string;
  exportElementClass: string;
};

const ignoreFolders = ["base", "config", "story"];
const allowedComponentFileExtensions = ["js", "ts", "tsx"];
const componentObjects: ComponentObject[] = [];

export const collectComponentObjects = (path: string, ignoreFoldersOverride?: string[]) => {
  const currentFolder = fs.readdirSync(path);

  currentFolder.forEach(childPath => {
    if (fs.statSync(`${path}/${childPath}`).isFile()) {
      if (isFileAComponent(childPath)) {
        componentObjects.push(makeComponentObject(path, childPath));
      }
    } else {
      if (!(ignoreFoldersOverride ?? ignoreFolders).includes(childPath)) {
        collectComponentObjects(`${path}/${childPath}`, ignoreFoldersOverride);
      }
    }
  });

  return componentObjects.sort((a, b) => a.importComponent.localeCompare(b.importComponent));
};

const isFileAComponent = (filename: string) => {
  const numberOfDotsInFilename = filename.split(".").length - 1;
  const fileExtension = getFileExtension(filename);
  const hasFileExtension = typeof fileExtension !== "undefined";

  switch (true) {
    case !hasFileExtension:
      return false;
    case numberOfDotsInFilename > 1:
      return false;
    case !allowedComponentFileExtensions.includes(fileExtension):
      return false;
  }
  return true;
};

const makeComponentObject = (path: string, filename: string) => {
  const filenameWithoutExtension = getFilenameWithoutExtension(filename);
  const pathWithoutSrc = path.replace("src/", "");
  const prefixedComponentName = `Kobber${filenameWithoutExtension}`;

  return {
    importComponent: `${filenameWithoutExtension} as ${prefixedComponentName}`,
    importPath: `${pathWithoutSrc}/${filenameWithoutExtension}`,
    exportName: filenameWithoutExtension,
    exportTagName: changeCaseTo(prefixedComponentName, "kebab"),
    exportElementClass: prefixedComponentName,
  };
};

export const autogenerateHeader = (filePath: string) =>
  `/* Autogenerated in ${filePath?.split("kobber-components")[1]} */\n\n`;
