/* Autogenerated in /build-scripts/list-react-components.ts */

"use client";

import { createComponent } from "@lit/react";
import * as React from "react";
 
import { Accordion as KobberAccordion } from "./accordion/Accordion";
import { AspectRatio as KobberAspectRatio } from "./aspect-ratio/AspectRatio";
import { Badge as KobberBadge } from "./badge/Badge";
import { BadgeIcon as KobberBadgeIcon } from "./badge-icon/BadgeIcon";
import { BoxLayout as KobberBoxLayout } from "./layouts/box-layout/BoxLayout";
import { Button as KobberButton } from "./button/Button";
import { CardLayout as KobberCardLayout } from "./layouts/card-layout/CardLayout";
import { CardLayoutColumnAspectRatio as KobberCardLayoutColumnAspectRatio } from "./layouts/card-layout/CardLayoutColumnAspectRatio";
import { Carousel as KobberCarousel } from "./carousel/Carousel";
import { CarouselButton as KobberCarouselButton } from "./carousel/CarouselButton";
import { CheckboxGroup as KobberCheckboxGroup } from "./checkbox/checkbox-group/CheckboxGroup";
import { CheckboxInput as KobberCheckboxInput } from "./checkbox/checkbox-input/CheckboxInput";
import { Divider as KobberDivider } from "./divider/Divider";
import { Dropdown as KobberDropdown } from "./dropdown/Dropdown";
import { Grid as KobberGrid } from "./grid/Grid";
import { GridColumn as KobberGridColumn } from "./grid/GridColumn";
import { GridColumnAspectRatio as KobberGridColumnAspectRatio } from "./grid/GridColumnAspectRatio";
import { Heading as KobberHeading } from "./text/heading/Heading";
import { HorizontalLayout as KobberHorizontalLayout } from "./layouts/horizontal-layout/HorizontalLayout";
import { HorizontalLayoutColumn as KobberHorizontalLayoutColumn } from "./layouts/horizontal-layout/HorizontalLayoutColumn";
import { Ingress as KobberIngress } from "./text/ingress/Ingress";
import { Link as KobberLink } from "./link/Link";
import { List as KobberList } from "./list/List";
import { ListItem as KobberListItem } from "./list/ListItem";
import { ProgressBar as KobberProgressBar } from "./progress-bar/ProgressBar";
import { ProgressBarItem as KobberProgressBarItem } from "./progress-bar/ProgressBarItem";
import { RadioGroup as KobberRadioGroup } from "./radio/radio-group/RadioGroup";
import { RadioInput as KobberRadioInput } from "./radio/radio-input/RadioInput";
import { RadioInputControl as KobberRadioInputControl } from "./radio/radio-input-control/RadioInputControl";
import { TextLink as KobberTextLink } from "./text/text-link/TextLink";
import { TextWrapper as KobberTextWrapper } from "./text/text-wrapper/TextWrapper";
import { ThemeContext as KobberThemeContext } from "./theme-context-provider/ThemeContext"; 

export const Accordion = createComponent({
  tagName: "kobber-accordion",
  elementClass: KobberAccordion,
  react: React,
});

export const AspectRatio = createComponent({
  tagName: "kobber-aspect-ratio",
  elementClass: KobberAspectRatio,
  react: React,
});

export const Badge = createComponent({
  tagName: "kobber-badge",
  elementClass: KobberBadge,
  react: React,
});

export const BadgeIcon = createComponent({
  tagName: "kobber-badge-icon",
  elementClass: KobberBadgeIcon,
  react: React,
});

export const BoxLayout = createComponent({
  tagName: "kobber-box-layout",
  elementClass: KobberBoxLayout,
  react: React,
});

export const Button = createComponent({
  tagName: "kobber-button",
  elementClass: KobberButton,
  react: React,
});

export const CardLayout = createComponent({
  tagName: "kobber-card-layout",
  elementClass: KobberCardLayout,
  react: React,
});

export const CardLayoutColumnAspectRatio = createComponent({
  tagName: "kobber-card-layout-column-aspect-ratio",
  elementClass: KobberCardLayoutColumnAspectRatio,
  react: React,
});

export const Carousel = createComponent({
  tagName: "kobber-carousel",
  elementClass: KobberCarousel,
  react: React,
});

export const CarouselButton = createComponent({
  tagName: "kobber-carousel-button",
  elementClass: KobberCarouselButton,
  react: React,
});

export const CheckboxGroup = createComponent({
  tagName: "kobber-checkbox-group",
  elementClass: KobberCheckboxGroup,
  react: React,
});

export const CheckboxInput = createComponent({
  tagName: "kobber-checkbox-input",
  elementClass: KobberCheckboxInput,
  react: React,
});

export const Divider = createComponent({
  tagName: "kobber-divider",
  elementClass: KobberDivider,
  react: React,
});

export const Dropdown = createComponent({
  tagName: "kobber-dropdown",
  elementClass: KobberDropdown,
  react: React,
});

export const Grid = createComponent({
  tagName: "kobber-grid",
  elementClass: KobberGrid,
  react: React,
});

export const GridColumn = createComponent({
  tagName: "kobber-grid-column",
  elementClass: KobberGridColumn,
  react: React,
});

export const GridColumnAspectRatio = createComponent({
  tagName: "kobber-grid-column-aspect-ratio",
  elementClass: KobberGridColumnAspectRatio,
  react: React,
});

export const Heading = createComponent({
  tagName: "kobber-heading",
  elementClass: KobberHeading,
  react: React,
});

export const HorizontalLayout = createComponent({
  tagName: "kobber-horizontal-layout",
  elementClass: KobberHorizontalLayout,
  react: React,
});

export const HorizontalLayoutColumn = createComponent({
  tagName: "kobber-horizontal-layout-column",
  elementClass: KobberHorizontalLayoutColumn,
  react: React,
});

export const Ingress = createComponent({
  tagName: "kobber-ingress",
  elementClass: KobberIngress,
  react: React,
});

export const Link = createComponent({
  tagName: "kobber-link",
  elementClass: KobberLink,
  react: React,
});

export const List = createComponent({
  tagName: "kobber-list",
  elementClass: KobberList,
  react: React,
});

export const ListItem = createComponent({
  tagName: "kobber-list-item",
  elementClass: KobberListItem,
  react: React,
});

export const ProgressBar = createComponent({
  tagName: "kobber-progress-bar",
  elementClass: KobberProgressBar,
  react: React,
});

export const ProgressBarItem = createComponent({
  tagName: "kobber-progress-bar-item",
  elementClass: KobberProgressBarItem,
  react: React,
});

export const RadioGroup = createComponent({
  tagName: "kobber-radio-group",
  elementClass: KobberRadioGroup,
  react: React,
});

export const RadioInput = createComponent({
  tagName: "kobber-radio-input",
  elementClass: KobberRadioInput,
  react: React,
});

export const RadioInputControl = createComponent({
  tagName: "kobber-radio-input-control",
  elementClass: KobberRadioInputControl,
  react: React,
});

export const TextLink = createComponent({
  tagName: "kobber-text-link",
  elementClass: KobberTextLink,
  react: React,
});

export const TextWrapper = createComponent({
  tagName: "kobber-text-wrapper",
  elementClass: KobberTextWrapper,
  react: React,
});

export const ThemeContext = createComponent({
  tagName: "kobber-theme-context",
  elementClass: KobberThemeContext,
  react: React,
});
