import { Accordion } from "./accordion/Accordion.react";
import { Button } from "./button/Button.react";
import { CheckboxInput } from "./checkbox/checkboxInput/CheckboxInput.react";
import { TextWrapper } from "./text/text-wrapper/TextWrapper.react";
import { TextLink } from "./text/text-link/TextLink.react";
import { Heading } from "./text/heading/Heading.react";
import { Ingress } from "./text/ingress/Ingress.react";
import { Link } from "./link/Link.react";
import { List } from "./list/List.react";
import { ListItem } from "./list/ListItem.react";
import { RadioGroup, RadioInput, RadioInputControl } from "./radio/index.react";
import { IconFormChecked, IconFormIndeterminate, IconFormRadio } from "./internal-icons/index.react";
import { Badge } from "./badge-new/Badge.react";

export const KobberTextWrapper = TextWrapper;
export const KobberTextLink = TextLink;
export const KobberBadge = Badge;

export const KobberHeading = Heading;
export const KobberIngress = Ingress;
export const KobberButton = Button;
export const KobberCheckboxInput = CheckboxInput;
export const KobberLink = Link;
export const KobberAccordion = Accordion;
export const KobberList = List;
export const KobberListItem = ListItem;
export const KobberRadioGroup = RadioGroup;
export const KobberRadioInput = RadioInput;
export const KobberRadioInputControl = RadioInputControl;
export const InternalIconFormChecked = IconFormChecked;
export const InternalIconFormIndeterminate = IconFormIndeterminate;
export const InternalIconFormRadio = IconFormRadio;
