import { Accordion } from "./accordion/Accordion.react";
import { Button } from "./button/Button.react";
import { TextWrapper } from "./text/text-wrapper/TextWrapper.react";
import { TextHighlight } from "./text/text-highlight/TextHighlight.react";
import { TextLink } from "./text/text-link/TextLink.react";
import { Heading } from "./text/heading/Heading.react";
import { Ingress } from "./text/ingress/Ingress.react";
import { Link } from "./link/Link.react";
import { List } from "./list/List.react";
import { ListItem } from "./list/ListItem.react";
import { RadioGroup, RadioInput, RadioInputControl } from "./radio";

export const KobberTextWrapper = TextWrapper;
export const KobberTextHighlight = TextHighlight;
export const KobberTextLink = TextLink;
export const KobberHeading = Heading;
export const KobberIngress = Ingress;
export const KobberButton = Button;
export const KobberLink = Link;
export const KobberAccordion = Accordion;
export const KobberList = List;
export const KobberListItem = ListItem;
export const KobberRadioGroup = RadioGroup;
export const KobberRadioInput = RadioInput;
export const KobberRadioInputControl = RadioInputControl;
