name: Github wiki

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - packages/kobber-components/**
      - .github/workflows/github-wiki.yml

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup install
        run: corepack enable

      - name: Install
        run: yarn

      - name: Build
        run: yarn build --filter @gyldendal/kobber-components

      - name: Typedoc
        working-directory: packages/kobber-components
        run: yarn typedoc

      - name: Generate wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4.4.0
        with:
          path: packages/kobber-components/docs/
