name: Github wiki
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - packages/kobber-components/**
      - .github/workflows/github-wiki.yml
concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup install
        run: corepack enable

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Typedoc
        working-directory: packages/kobber-components
        run: yarn typedoc

      - name: Generate wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4.4.0
        with:
          path: packages/kobber-components/docs/
